[workspace]
members = [
  "contracts/abi-test",
  "executor/runner",
  "executor/runtime",
  "json-proof",
  "sdk/abi" ,
  # "sdk/base",
  "sdk/core",
  "sdk/macros",
  "kv-store"
]
resolver = "2"


[workspace.dependencies]
anyhow = "1.0"
bs58 = "0.5"
log = "0.4"
postcard = { version = "1.1", features = ["alloc"] }
rand = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
thiserror = "2.0"
