[workspace]
members = [
  "examples/abi-test",
  "examples/abi-test-swagent",
  "examples/lazyvec-test",
  "examples/flipper",
  "executor/runner",
  "executor/runtime",
  "json-proof",
  "sdk/abi" ,
  "sdk/core",
  "sdk/macros",
  "kv-store",
  "primitives/hash",
  "primitives/id-types",
]
resolver = "2"

[workspace.dependencies]
# Export own crates
borderless = { path = "sdk/core" }
borderless-abi = { path = "sdk/abi" }
borderless-sdk-macros = { path = "sdk/macros" }
borderless-id-types = { path = "primitives/id-types" }
borderless-hash = { path = "primitives/hash" }
borderless-kv-store = { path = "kv-store" }
borderless-runtime = { path = "executor/runtime" }

# External dependencies
anyhow = "1.0"
log = "0.4"
postcard = { version = "1.1", features = ["alloc"] }
rand = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
thiserror = "2.0"
uuid = "1.16"
