[package]
name = "currency-4217"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
rand.workspace = true

[features]
serde = [ "dep:serde" ]
