[package]
name = "abi-test-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
borderless-sdk-core = { path = "../../sdk/core" }
borderless-sdk = { path = "../../sdk/base" }
