[package]
name = "borderless-format"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
borderless-hash = { path = "../hash" }
serde_bytes = "0.11"
async-trait = "0.1"
