[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
abi = { path = "../abi" }
#macros = { path = "../macros" }
anyhow = "1.0.92"
postcard = { version = "1.0.10", features = ["use-std"] }
serde = "1.0.214"
serde_json = "1.0.133"
