[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
borderless-sdk = { path = "../../sdk/base" }
lmdb = "0.8.0"
nohash = "0.2.0"
log.workspace = true
rand.workspace = true
wasmtime = "30.0.2"
