[package]
name = "borderless-sdk-core"
version = "0.1.0"
edition = "2021"

[dependencies]
borderless-abi = { path = "../abi" }
postcard = { version = "1.1.1", features = ["alloc"] }
serde.workspace = true
