[package]
name = "borderless-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
borderless-abi = { path = "../abi" }
postcard = { version = "1.1.1", features = ["alloc"] }
serde.workspace = true
serde_json.workspace = true
uuid = { version = "1.16.0", features = ["serde", "v8"] }

[dev-dependencies]
uuid = { version = "1.16.0", features = ["serde", "v8", "v4"] }

[features]
default = []
generate_ids = ["uuid/v4"]
